trigger:
- trunk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: '1. Instalar Node.js'

- script: npm ci
  displayName: '2. Instalar librerías del proyecto'

- script: npx playwright install --with-deps
  displayName: 'Instalar Navegadores de Playwright'

- script: |
    npx playwright test
  displayName: '3. Ejecutar Playwright E2E'
  continueOnError: true


- task: PublishHtmlReport@1
  condition: always()
  inputs:
    reportDir: '$(System.DefaultWorkingDirectory)/playwright-report/index.html'
    tabName: 'Reporte Playwright'
  displayName: '4. Publicar Pestaña HTML'

- task: AzureCLI@2
  displayName: 'Subir reporte desde Linux a Azure Storage'
  inputs:
    azureSubscription: 'Suscripción de Azure 1' # Tu Service Connection ARM
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Usamos az storage blob upload-batch para subir toda la carpeta
      az storage blob upload-batch \
        --destination '$web' \
        --source 'playwright-report' \
        --account-name 'adrojasreports' \
        --auth-mode login
  condition: always()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'results.xml'
  displayName: '5. Publicar Resultados de Pruebas'